# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Update HTM of L2
        
      - name: Download Saxon-HE
        run:  curl https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.1/Saxon-HE-10.1.jar > saxon.jar
        
      - name: Perform XSL Transformation
        run: java -cp ./saxon.jar net.sf.saxon.Transform -s:l2/l2.xml -xsl:l2/l2.xsl -o:l2/l2.htm

      - name: Commit Changes
        run:  |
          git add l2/l2.htm
          git diff
          git config user.email "maik@btmx.net"
          git config user.name "GitHub Action Bot"
          git commit -m "Updated HTM of L2" -a || echo "No changes to commit"
          git push
